package com.kidsgalaxy.data.remote

import android.content.Context
import android.util.Log
import com.kidsgalaxy.BuildConfig
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import java.io.IOException
import java.security.KeyStore
import java.security.cert.CertificateFactory
import java.util.concurrent.TimeUnit
import javax.net.ssl.KeyManagerFactory
import javax.net.ssl.SSLContext
import javax.net.ssl.TrustManagerFactory
import javax.net.ssl.X509TrustManager

/**
 * Builds the [PlanetApi] client.
 *
 * Two transport modes:
 *  - **Cleartext HTTP** (debug / lab): the Pi hotspot is a closed network.
 *  - **Mutual TLS** (release / recommended): the tablet presents a client
 *    certificate and pins trust to the project's own CA. No password or token
 *    is ever exchanged at runtime - the PKCS#12 password is install-time only.
 *
 * For mTLS, place the files generated by `pi-server/certs/generate_certs.sh` in
 * `app/src/main/assets/`:
 *   - `client.p12` (tablet identity)
 *   - `ca.crt`     (so the tablet trusts the Pi's self-signed server cert)
 *
 * These are deliberately NOT committed - see .gitignore.
 */
object ApiClient {
    private const val TAG = "KidsGalaxyApi"
    private const val CLIENT_CERT_ASSET = "client.p12"
    private const val CA_CERT_ASSET = "ca.crt"

    /** Thrown when mTLS is required but the certificate assets are absent/unusable. */
    class CertificateSetupException(
        message: String,
        cause: Throwable? = null,
    ) : IOException(message, cause)

    fun create(
        context: Context,
        baseUrl: String = BuildConfig.SERVER_BASE_URL,
        useMutualTls: Boolean = BuildConfig.USE_MTLS,
    ): PlanetApi {
        val builder =
            OkHttpClient
                .Builder()
                .connectTimeout(8, TimeUnit.SECONDS)
                .readTimeout(20, TimeUnit.SECONDS)
                .writeTimeout(20, TimeUnit.SECONDS)
                .retryOnConnectionFailure(true)

        // Request/response logging is a debug-only aid; it must never ship enabled.
        if (BuildConfig.DEBUG) {
            builder.addInterceptor(
                HttpLoggingInterceptor().apply {
                    level = HttpLoggingInterceptor.Level.BASIC
                },
            )
        }

        if (useMutualTls) {
            applyMutualTls(context, builder)
        }

        return Retrofit
            .Builder()
            .baseUrl(baseUrl.trimEnd('/') + "/")
            .client(builder.build())
            .addConverterFactory(GsonConverterFactory.create())
            .build()
            .create(PlanetApi::class.java)
    }

    /**
     * Configures the client certificate (tablet identity) and pins trust to our CA.
     */
    private fun applyMutualTls(
        context: Context,
        builder: OkHttpClient.Builder,
    ) {
        try {
            val keyManagers = loadClientIdentity(context)
            val trustManager = loadCaTrustManager(context)

            val sslContext =
                SSLContext.getInstance("TLS").apply {
                    init(keyManagers, arrayOf(trustManager), null)
                }

            builder.sslSocketFactory(sslContext.socketFactory, trustManager)
            Log.i(TAG, "mTLS enabled - presenting client certificate")
        } catch (e: CertificateSetupException) {
            throw e
        } catch (e: Exception) {
            throw CertificateSetupException(
                "Could not initialise mTLS. Ensure $CLIENT_CERT_ASSET and " +
                    "$CA_CERT_ASSET are present in app assets.",
                e,
            )
        }
    }

    private fun loadClientIdentity(context: Context): Array<javax.net.ssl.KeyManager> {
        val password = BuildConfig.CLIENT_CERT_PASSWORD.toCharArray()
        val keyStore =
            KeyStore.getInstance("PKCS12").apply {
                try {
                    context.assets.open(CLIENT_CERT_ASSET).use { load(it, password) }
                } catch (e: IOException) {
                    throw CertificateSetupException(
                        "Missing client certificate asset '$CLIENT_CERT_ASSET'. " +
                            "Run pi-server/certs/generate_certs.sh and copy it into " +
                            "android/app/src/main/assets/.",
                        e,
                    )
                }
            }

        return KeyManagerFactory
            .getInstance(KeyManagerFactory.getDefaultAlgorithm())
            .apply { init(keyStore, password) }
            .keyManagers
    }

    /**
     * Trusts only the KidsGalaxy CA. The Pi's certificate is self-signed, so the
     * system trust store would reject it; pinning to our CA is both necessary and
     * stronger than trusting every public root.
     */
    private fun loadCaTrustManager(context: Context): X509TrustManager {
        val caCertificate =
            try {
                context.assets.open(CA_CERT_ASSET).use { input ->
                    CertificateFactory.getInstance("X.509").generateCertificate(input)
                }
            } catch (e: IOException) {
                throw CertificateSetupException(
                    "Missing CA certificate asset '$CA_CERT_ASSET'.",
                    e,
                )
            }

        val trustStore =
            KeyStore.getInstance(KeyStore.getDefaultType()).apply {
                load(null, null)
                setCertificateEntry("kids-galaxy-ca", caCertificate)
            }

        val factory =
            TrustManagerFactory
                .getInstance(TrustManagerFactory.getDefaultAlgorithm())
                .apply { init(trustStore) }

        return factory.trustManagers.filterIsInstance<X509TrustManager>().firstOrNull()
            ?: throw CertificateSetupException("No X509TrustManager available for the CA.")
    }
}
